const STOCKS = ["AKBNK","ARCLK","ASELS","BIMAS","DOHOL","EKGYO","EREGL","FROTO","GARAN","HALKB","ISCTR","KCHOL","KOZAA","KOZAL","KRDMD","PETKM","PGSUS","SAHOL","SISE","SODA","TAVHL","TCELL","THYAO","TKFEN","TOASO","TSKB","TTKOM","TUPRS","VAKBN","YKBNK"];

module.exports = { 
    STOCKS,
}
